//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_History
    {
        public int ID { get; set; }
        public int ID_Order { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
